apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.0.x"
  test:
    enable: false
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    replicaCount: 2
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 16Mi
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/affinity: "cookie"
        nginx.ingress.kubernetes.io/affinity-mode: "persistent"
      hosts:
        - paths:
            - path: /
              pathType: ImplementationSpecific
    logLevel: debug
